name: Generate PDF

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install gdebi-core xvfb -y

          curl -LOs https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.bionic_amd64.deb
          yes | sudo gdebi wkhtmltox_0.12.5-1.bionic_amd64.deb

      - name: Cache stack folder
        id: stack
        uses: actions/cache@v2
        with:
          path: ~/.stack
          key: stack

      - name: Generate PDF
        run: |
          make clean
          make generate filename=jeff-cheah.pdf

      - name: Publish to s3 bucket
        run: |
          aws s3 cp jeff-cheah.pdf s3://resume-jeffhappily --acl public-read
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
